
trigger:
- task

pool:
  name: ads_Windows

stages:
- stage: BuildApp
  displayName: 'Build App'
  
  jobs:
  - job: ConsoleApp
    displayName: 'Build Console App'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet'

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '$(solution)'

    - task: SonarQubePrepare@5
      displayName: 'Prepare SonarQube Connection'
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'MSBuild'
        projectKey: 'TestFarah'
        projectName: 'TestFarah'
    
    - task: VSBuild@1
      displayName: 'Build Solution'
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: SonarQubeAnalyze@5
      displayName: 'SonarQube Analyze'

    - task: CopyFiles@2
      displayName: 'Copy Files to $(Build.ArtifactStagingDirectory)'
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**/bin/Debug/**'
        targetFolder: '$(Build.ArtifactStagingDirectory)' 

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'DropHelloWorld'

    - task: SonarQubePublish@5
      displayName: 'Publish SonarQube Result task'
      inputs:
        pollingTimeoutSec: '300'
        
- stage: DeployApp
  displayName: 'Deploy App'

  jobs:
  - job: DeployConsoleApp
    displayName: 'Deploy Console App'

    pool:
      name: test-farah

    steps:

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'DropHelloWorld'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy Files to D:\ on the agent Host'
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)'
        Contents: '**'
        TargetFolder: 'D:\Hello'
    
    - task: CmdLine@2
      displayName: 'Run Console App'
      inputs:
        script: 'HelloWorld.exe'
        workingDirectory: 'D:\Hello\DropHelloWorld\bin\Debug\net6.0'
        